import type { BuildingDefinition } from "../types/building.js";

export const BUILDINGS: BuildingDefinition[] = [
  {
    type: "lumbermill",
    name: "Lumbermill",
    description:
      "Saws and lumberyards turn the forest's bounty into shaped timber. Wood is the lifeblood of every early structure, palisade, and siege engine — without it, your realm cannot grow. Each level deepens the cut and trains more woodcutters.",
    maxLevel: 10,
    baseCost: { wood: 50, stone: 30, iron: 0, gold: 10 },
    costMultiplier: 1.5,
    baseBuildTicks: 1,
    buildTicksMultiplier: 1.5,
    produces: { resource: "wood", baseRate: 10 },
  },
  {
    type: "quarry",
    name: "Quarry",
    description:
      "Stonecutters chisel and haul masonry blocks from the bedrock below your fief. Stone defines walls, foundations, and the lasting monuments of your reign — every great keep begins as raw rock pried from the cliffs. Higher levels open new galleries and double-shift labor.",
    maxLevel: 10,
    baseCost: { wood: 60, stone: 20, iron: 10, gold: 10 },
    costMultiplier: 1.5,
    baseBuildTicks: 1,
    buildTicksMultiplier: 1.5,
    produces: { resource: "stone", baseRate: 8 },
  },
  {
    type: "mine",
    name: "Iron Mine",
    description:
      "Deep shafts plunge into iron-bearing rock, where smelters and forge-hands draw out the dark ore that becomes blades, mail, and arrowheads. Iron is scarce and slow to extract, but no army of consequence marches without it. Upgrades sink fresh tunnels and improve the bellows.",
    maxLevel: 10,
    baseCost: { wood: 80, stone: 60, iron: 0, gold: 20 },
    costMultiplier: 1.6,
    baseBuildTicks: 2,
    buildTicksMultiplier: 1.5,
    produces: { resource: "iron", baseRate: 5 },
  },
  {
    type: "farm",
    name: "Farm",
    description:
      "Tilled fields, orchards, and livestock pens supply the grain and meat that keep your peasants and soldiers alive. A starving army loses morale before it loses battles — invest early in food, or watch your fief wither. Each upgrade reclaims more land and refines the harvest.",
    maxLevel: 10,
    baseCost: { wood: 40, stone: 10, iron: 0, gold: 5 },
    costMultiplier: 1.4,
    baseBuildTicks: 1,
    buildTicksMultiplier: 1.4,
    produces: { resource: "food", baseRate: 15 },
  },
  {
    type: "market",
    name: "Market",
    description:
      "Stalls, scribes, and caravan masters convert your surplus into hard coin. The market funds mercenaries, diplomacy, and the silken bribes that win wars without battles. Higher levels attract richer traders from distant realms.",
    maxLevel: 10,
    baseCost: { wood: 100, stone: 80, iron: 20, gold: 0 },
    costMultiplier: 1.6,
    baseBuildTicks: 2,
    buildTicksMultiplier: 1.5,
    produces: { resource: "gold", baseRate: 8 },
  },
  {
    type: "barracks",
    name: "Barracks",
    description:
      "The drill yard and armory where commoners are forged into soldiers. The barracks unlocks militia, men-at-arms, and longbowmen — the steel backbone of any standing host. Higher levels train more disciplined ranks and unlock advanced infantry doctrines.",
    maxLevel: 10,
    baseCost: { wood: 120, stone: 80, iron: 30, gold: 30 },
    costMultiplier: 1.6,
    baseBuildTicks: 2,
    buildTicksMultiplier: 1.5,
  },
  {
    type: "wall",
    name: "Wall",
    description: "Fortifies your fief against attacks.",
    maxLevel: 10,
    baseCost: { wood: 60, stone: 150, iron: 20, gold: 20 },
    costMultiplier: 1.7,
    baseBuildTicks: 3,
    buildTicksMultiplier: 1.6,
  },
  {
    type: "keep",
    name: "Keep",
    description: "The heart of your fief. Upgrading unlocks new buildings.",
    maxLevel: 10,
    baseCost: { wood: 200, stone: 200, iron: 50, gold: 100 },
    costMultiplier: 2.0,
    baseBuildTicks: 3,
    buildTicksMultiplier: 1.8,
  },
  {
    type: "stable",
    name: "Stable",
    description: "Allows training of cavalry units.",
    maxLevel: 5,
    baseCost: { wood: 150, stone: 100, iron: 60, gold: 50 },
    costMultiplier: 1.7,
    baseBuildTicks: 2,
    buildTicksMultiplier: 1.5,
    requires: "barracks",
  },
  {
    type: "workshop",
    name: "Workshop",
    description: "Enables construction of siege engines.",
    maxLevel: 5,
    baseCost: { wood: 200, stone: 120, iron: 80, gold: 60 },
    costMultiplier: 1.8,
    baseBuildTicks: 3,
    buildTicksMultiplier: 1.6,
    requires: "barracks",
  },
  {
    type: "watchtower",
    name: "Watchtower",
    description: "Increases scouting range and provides raid warnings.",
    maxLevel: 5,
    baseCost: { wood: 80, stone: 100, iron: 10, gold: 15 },
    costMultiplier: 1.5,
    baseBuildTicks: 2,
    buildTicksMultiplier: 1.4,
  },
  {
    type: "granary",
    name: "Granary",
    description: "Increases food storage capacity.",
    maxLevel: 10,
    baseCost: { wood: 70, stone: 40, iron: 5, gold: 10 },
    costMultiplier: 1.4,
    baseBuildTicks: 1,
    buildTicksMultiplier: 1.3,
  },
  {
    type: "warehouse",
    name: "Warehouse",
    description: "Increases storage capacity for wood, stone, iron, and gold.",
    maxLevel: 10,
    baseCost: { wood: 80, stone: 50, iron: 10, gold: 15 },
    costMultiplier: 1.4,
    baseBuildTicks: 1,
    buildTicksMultiplier: 1.3,
  },
];

export const BUILDING_MAP = Object.fromEntries(
  BUILDINGS.map((b) => [b.type, b])
) as Record<string, BuildingDefinition>;
