import type { BuildingDefinition } from "../types/building.js";

export const BUILDINGS: BuildingDefinition[] = [
  {
    type: "lumbermill",
    name: "Lumbermill",
    description: "Produces wood from nearby forests.",
    maxLevel: 10,
    baseCost: { wood: 50, stone: 30, iron: 0, gold: 10 },
    costMultiplier: 1.5,
    baseBuildTicks: 5,
    buildTicksMultiplier: 1.3,
    produces: { resource: "wood", baseRate: 10 },
  },
  {
    type: "quarry",
    name: "Quarry",
    description: "Extracts stone from the earth.",
    maxLevel: 10,
    baseCost: { wood: 60, stone: 20, iron: 10, gold: 10 },
    costMultiplier: 1.5,
    baseBuildTicks: 6,
    buildTicksMultiplier: 1.3,
    produces: { resource: "stone", baseRate: 8 },
  },
  {
    type: "mine",
    name: "Iron Mine",
    description: "Mines iron ore from deep veins.",
    maxLevel: 10,
    baseCost: { wood: 80, stone: 60, iron: 0, gold: 20 },
    costMultiplier: 1.6,
    baseBuildTicks: 8,
    buildTicksMultiplier: 1.4,
    produces: { resource: "iron", baseRate: 5 },
  },
  {
    type: "farm",
    name: "Farm",
    description: "Grows food to feed your people and troops.",
    maxLevel: 10,
    baseCost: { wood: 40, stone: 10, iron: 0, gold: 5 },
    costMultiplier: 1.4,
    baseBuildTicks: 4,
    buildTicksMultiplier: 1.2,
    produces: { resource: "food", baseRate: 15 },
  },
  {
    type: "market",
    name: "Market",
    description: "Generates gold through trade.",
    maxLevel: 10,
    baseCost: { wood: 100, stone: 80, iron: 20, gold: 0 },
    costMultiplier: 1.6,
    baseBuildTicks: 10,
    buildTicksMultiplier: 1.4,
    produces: { resource: "gold", baseRate: 8 },
  },
  {
    type: "barracks",
    name: "Barracks",
    description: "Allows training of infantry and militia.",
    maxLevel: 10,
    baseCost: { wood: 120, stone: 80, iron: 30, gold: 30 },
    costMultiplier: 1.6,
    baseBuildTicks: 10,
    buildTicksMultiplier: 1.5,
  },
  {
    type: "wall",
    name: "Wall",
    description: "Fortifies your fief against attacks.",
    maxLevel: 10,
    baseCost: { wood: 60, stone: 150, iron: 20, gold: 20 },
    costMultiplier: 1.7,
    baseBuildTicks: 15,
    buildTicksMultiplier: 1.5,
  },
  {
    type: "keep",
    name: "Keep",
    description: "The heart of your fief. Upgrading unlocks new buildings.",
    maxLevel: 10,
    baseCost: { wood: 200, stone: 200, iron: 50, gold: 100 },
    costMultiplier: 2.0,
    baseBuildTicks: 20,
    buildTicksMultiplier: 1.8,
  },
  {
    type: "stable",
    name: "Stable",
    description: "Allows training of cavalry units.",
    maxLevel: 5,
    baseCost: { wood: 150, stone: 100, iron: 60, gold: 50 },
    costMultiplier: 1.7,
    baseBuildTicks: 12,
    buildTicksMultiplier: 1.5,
    requires: "barracks",
  },
  {
    type: "workshop",
    name: "Workshop",
    description: "Enables construction of siege engines.",
    maxLevel: 5,
    baseCost: { wood: 200, stone: 120, iron: 80, gold: 60 },
    costMultiplier: 1.8,
    baseBuildTicks: 15,
    buildTicksMultiplier: 1.6,
    requires: "barracks",
  },
  {
    type: "watchtower",
    name: "Watchtower",
    description: "Increases scouting range and provides raid warnings.",
    maxLevel: 5,
    baseCost: { wood: 80, stone: 100, iron: 10, gold: 15 },
    costMultiplier: 1.5,
    baseBuildTicks: 8,
    buildTicksMultiplier: 1.3,
  },
  {
    type: "granary",
    name: "Granary",
    description: "Increases food storage capacity.",
    maxLevel: 10,
    baseCost: { wood: 70, stone: 40, iron: 5, gold: 10 },
    costMultiplier: 1.4,
    baseBuildTicks: 5,
    buildTicksMultiplier: 1.2,
  },
  {
    type: "warehouse",
    name: "Warehouse",
    description: "Increases storage capacity for wood, stone, iron, and gold.",
    maxLevel: 10,
    baseCost: { wood: 80, stone: 50, iron: 10, gold: 15 },
    costMultiplier: 1.4,
    baseBuildTicks: 6,
    buildTicksMultiplier: 1.2,
  },
];

export const BUILDING_MAP = Object.fromEntries(
  BUILDINGS.map((b) => [b.type, b])
) as Record<string, BuildingDefinition>;
