import type { TroopDefinition } from "../types/troop.js";

export const TROOPS: TroopDefinition[] = [
  {
    type: "militia",
    name: "Militia",
    description: "Cheap peasant levies. Weak but fast to recruit.",
    attack: 2,
    defense: 3,
    upkeep: 1,
    baseCost: { wood: 10, stone: 0, iron: 5, gold: 5, food: 20 },
    baseRecruitTicks: 1,
    requiresBuilding: "barracks",
    requiresBuildingLevel: 1,
  },
  {
    type: "spearman",
    name: "Spearman",
    description: "Lancer foot soldier — great defensive presence, hard counter to cavalry.",
    attack: 4,
    defense: 7,
    upkeep: 2,
    baseCost: { wood: 15, stone: 0, iron: 15, gold: 8, food: 25 },
    baseRecruitTicks: 2,
    requiresBuilding: "barracks",
    requiresBuildingLevel: 2,
  },
  {
    type: "infantry",
    name: "Infantry",
    description: "Well-trained foot soldiers. Balanced fighters.",
    attack: 5,
    defense: 6,
    upkeep: 2,
    baseCost: { wood: 15, stone: 0, iron: 20, gold: 10, food: 30 },
    baseRecruitTicks: 2,
    requiresBuilding: "barracks",
    requiresBuildingLevel: 3,
  },
  {
    type: "archer",
    name: "Archer",
    description: "Ranged units. Strong attack, weaker in melee.",
    attack: 7,
    defense: 3,
    upkeep: 2,
    baseCost: { wood: 25, stone: 0, iron: 10, gold: 15, food: 25 },
    baseRecruitTicks: 2,
    requiresBuilding: "barracks",
    requiresBuildingLevel: 5,
  },
  {
    type: "scout",
    name: "Scout",
    description: "Fast mounted explorers. Cheap, low combat strength, ideal for reconnaissance.",
    attack: 3,
    defense: 2,
    upkeep: 1,
    baseCost: { wood: 10, stone: 0, iron: 10, gold: 15, food: 25 },
    baseRecruitTicks: 1,
    requiresBuilding: "stable",
    requiresBuildingLevel: 1,
  },
  {
    type: "cavalry_light",
    name: "Light Cavalry",
    description: "Swift mounted skirmishers. Solid attack, modest defense.",
    attack: 9,
    defense: 5,
    upkeep: 3,
    baseCost: { wood: 20, stone: 0, iron: 25, gold: 30, food: 40 },
    baseRecruitTicks: 3,
    requiresBuilding: "stable",
    requiresBuildingLevel: 3,
  },
  {
    type: "cavalry_heavy",
    name: "Heavy Cavalry",
    description: "Armored knights. Devastating in shock combat, expensive to field.",
    attack: 14,
    defense: 10,
    upkeep: 5,
    baseCost: { wood: 30, stone: 0, iron: 50, gold: 60, food: 60 },
    baseRecruitTicks: 5,
    requiresBuilding: "stable",
    requiresBuildingLevel: 5,
  },
  {
    type: "catapult",
    name: "Catapult",
    description: "Siege engine. Devastating against fortifications.",
    attack: 20,
    defense: 2,
    upkeep: 6,
    baseCost: { wood: 80, stone: 40, iron: 50, gold: 60, food: 30 },
    baseRecruitTicks: 6,
    requiresBuilding: "workshop",
    requiresBuildingLevel: 1,
  },
];

export const TROOP_MAP = Object.fromEntries(
  TROOPS.map((t) => [t.type, t])
) as Record<string, TroopDefinition>;
